# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# ✅ 添加分页插件
plugins:
  - jekyll-paginate

# The language of the webpage
lang: en

# Timezone
timezone: Asia/Shanghai

# SEO Settings
title: Cryanskl
tagline: Output is cheap. Show me the prompt.
description: >-
  A personal blog by Cryanskl
url: "https://cryanskl.github.io"

github:
  username: cryanskl

social:
  name: cryanskl
  email: cryanskl@foxmail.com
  links:
    - https://github.com/cryanskl

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

pageviews:
  provider:

theme_mode: light

cdn: "https://zr-picture.oss-cn-shanghai.aliyuncs.com/"

avatar: "/assets/img/jerry.webp"
social_preview_image: "/assets/img/jerry.webp"

toc: true

comments:
  provider: giscus
  giscus:
    repo: cryanskl/cryanskl.github.io
    repo_id: R_kgDOORJ6bA
    category: Announcements
    category_id: DIC_kwDOORJ6bM4CorRk
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

assets:
  self_host:
    enabled: true
    env: 

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

# ✅ 分页配置
paginate: 10
paginate_path: "/page:num/"  # 加上分页路径模板

baseurl: ""

backgroud_animation: true

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed
  quiet_deps: true

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
